version: 2
jobs:
  audit_and_test:
    docker:
      - image: circleci/ruby:2.6.0-stretch
    steps:
      - checkout
      - run: sudo apt-get install build-essential curl file git
      - run: sudo adduser --disabled-password --gecos "" tapuser
      - run: su - tapuser
      - run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      - run: test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
      - run: test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
      - run: test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
      - run: echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
      - run: brew audit --new-formula Formula/*.rb
      - run: brew audit --strict --online Formula/*.rb
      - run: brew test Formula/*.rb
workflows:
  version: 2
  audit_test:
    jobs:
      - audit_and_test